### ISSUE TITLE
TODO Count 46 / FIXME count 2

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-edv-storage#10]
- [ ] TODO: rework test suite to avoid shared state
       Commit: (9a240c3) Add core files.
       File:  [test/mocha/20-http.js:71](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/20-http.js#L71)
       Dave Longley commented 4 months ago

  - [ ] TODO: do not require primary `keyAgreementKey` and `hmac` in the future
       Commit: (9a240c3) Add core files.
       File:  [schemas/bedrock-edv-storage.js:9](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/schemas/bedrock-edv-storage.js#L9)
       Dave Longley commented 4 months ago

  - [ ] TODO: store chunks as files instead of documents
       Commit: (9a240c3) Add core files.
       File:  [lib/storage.js:607](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L607)
       Dave Longley commented 4 months ago

  - [ ] TODO: store chunks as files instead of documents
       Commit: (9a240c3) Add core files.
       File:  [lib/storage.js:571](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L571)
       Dave Longley commented 4 months ago

  - [ ] TODO: optimize retrieval of only sequence number
       Commit: (9a240c3) Add core files.
       File:  [lib/storage.js:492](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L492)
       Dave Longley commented 4 months ago

  - [ ] TODO: implement garbage collector worker that removes chunks with stale
       Commit: (9a240c3) Add core files.
       File:  [lib/storage.js:487](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L487)
       Dave Longley commented 4 months ago

  - [ ] TODO: what's the max offset here? Number.MAX_SAFE_INTEGER?
       Commit: (9a240c3) Add core files.
       File:  [lib/storage.js:472](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L472)
       Dave Longley commented 4 months ago

  - [ ] TODO: enable optional primary `keyAgreementKey` and `hmac` in the future
       Commit: (9a240c3) Add core files.
       File:  [lib/storage.js:120](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L120)
       Dave Longley commented 4 months ago

  - [ ] FIXME: can/should this be consolidated?
       Commit: (9a240c3) Add core files.
       File:  [lib/storage.js:67](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L67)
       Dave Longley commented 4 months ago

  - [ ] TODO: move into JSON schema validator
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:803](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L803)
       Dave Longley commented 4 months ago

  - [ ] TODO: support RsaSignature2018 and other suites?
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:680](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L680)
       Dave Longley commented 4 months ago

  - [ ] TODO: determine from parsing multibase key
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:567](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L567)
       Dave Longley commented 4 months ago

  - [ ] TODO: move to did-key lib
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:556](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L556)
       Dave Longley commented 4 months ago

  - [ ] TODO: some of the following code is a target for reusability in other
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:551](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L551)
       Dave Longley commented 4 months ago

  - [ ] TODO: add zcap validator
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:464](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L464)
       Dave Longley commented 4 months ago

  - [ ] TODO: need to determine how to filter the recipients to include
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:418](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L418)
       Dave Longley commented 4 months ago

  - [ ] TODO: add document ID to the chunk as well -- as a sanity check?
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:374](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L374)
       Dave Longley commented 4 months ago

  - [ ] TODO: need to determine how to filter the recipients to include
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:342](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L342)
       Dave Longley commented 4 months ago

  - [ ] TODO: database.hash() hmac IDs here and in `storage`?
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:308](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L308)
       Dave Longley commented 4 months ago

  - [ ] TODO: need to determine how to filter the recipients to include
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:248](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L248)
       Dave Longley commented 4 months ago

  - [ ] TODO: consider making this zcap authorized instead
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:139](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L139)
       Dave Longley commented 4 months ago

  - [ ] TODO: implement
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:101](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L101)
       Dave Longley commented 4 months ago

  - [ ] TODO: implement query validator
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:89](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L89)
       Dave Longley commented 4 months ago

  - [ ] TODO: endpoints for creating and deleting EDVs will only use
       Commit: (9a240c3) Add core files.
       File:  [lib/http.js:58](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L58)
       Dave Longley commented 4 months ago

       TODO Count          46
       FIXME Count         2
       Oldest Comment      4 months ago
       Oldest Commenter    Dave Longley
       Oldest Comment      TODO: rework test suite to avoid shared state

**Comment by JSAssassin** [comment]
Newest Report #46
