### ISSUE TITLE
TODO/FIXME Count 19

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/bedrock-edv-storage#46]
- [ ] TODO: do not use did:key but support a did:v1 based key.
      Commit: (6e309e8) Add tests.
      [test/mocha/helpers.js:319](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/helpers.js#L319)
      Matthew Collier commented 3 months ago

  - [ ] TODO: map `signer.type` to signature suite
      Commit: (0464898) Add a test helper for delegating zCaps.
      [test/mocha/helpers.js:293](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/helpers.js#L293)
      Andrew Jones commented 3 months ago

  - [ ] FIXME: make more restrictive, support `did:key` and `did:v1`
      Commit: (a4dd0e1) Update to latest webkms-client APIs.
      [test/mocha/helpers.js:248](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/helpers.js#L248)
      Matthew Collier commented 4 months ago

  - [ ] TODO: this more comprehensive test is to be completed later
     Commit: (a96680a) Re-implement passport stub.
     [test/mocha/19-revocation.js:163](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/19-revocation.js#L163)
     Matthew Collier commented 3 months ago

  - [ ] TODO: Move this to helpers.
     Commit: (35a7b80) Add test util to generate testers for zCap revocation tests.
     [test/mocha/19-revocation.js:36](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/19-revocation.js#L36)
     Andrew Jones commented 3 months ago

  - [ ] TODO: Rename this.
     Commit: (35a7b80) Add test util to generate testers for zCap revocation tests.
     [test/mocha/19-revocation.js:35](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/19-revocation.js#L35)
     Andrew Jones commented 3 months ago

  - [ ] FIXME: the current implementation does not check edv id
      Commit: (66f802c) Refactor test files.
      [test/mocha/18-remove.js:62](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/18-remove.js#L62)
      Matthew Collier commented 4 months ago

  - [ ] FIXME: the current implementation does not check edv id
      Commit: (66f802c) Refactor test files.
      [test/mocha/16-update.js:50](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/16-update.js#L50)
      Matthew Collier commented 4 months ago

  - [ ] FIXME: the current implementation does not check for a valid edv id
      Commit: (ee912ff) Add a count api to storage.
      [test/mocha/15-count.js:115](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/15-count.js#L115)
      Andrew L Jones commented 20 days ago

  - [ ] FIXME: current implementation does not check edv id
      Commit: (66f802c) Refactor test files.
      [test/mocha/14-get.js:44](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/14-get.js#L44)
      Matthew Collier commented 4 months ago

  - [ ] FIXME: the current implementation does not check for a valid edv id
      Commit: (66f802c) Refactor test files.
      [test/mocha/13-find.js:123](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/13-find.js#L123)
      Matthew Collier commented 4 months ago

  - [ ] FIXME: enable this test, current implementation does not test edv id
      Commit: (66f802c) Refactor test files.
      [test/mocha/12-insert.js:206](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/test/mocha/12-insert.js#L206)
      Matthew Collier commented 4 months ago

  - [ ] TODO: optimize retrieval of only sequence number
      Commit: (9a240c3) Add core files.
      [lib/storage.js:496](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L496)
      Dave Longley commented 9 months ago

  - [ ] TODO: implement garbage collector worker that removes chunks with stale
      Commit: (9a240c3) Add core files.
      [lib/storage.js:491](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L491)
      Dave Longley commented 9 months ago

  - [ ] FIXME: can/should this be consolidated?
      Commit: (9a240c3) Add core files.
      [lib/storage.js:64](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/storage.js#L64)
      Dave Longley commented 9 months ago

  - [ ] TODO: need to determine how to filter the recipients to include
      Commit: (9a240c3) Add core files.
      [lib/http.js:443](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L443)
      Dave Longley commented 9 months ago

  - [ ] TODO: add document ID to the chunk as well -- as a sanity check?
      Commit: (9a240c3) Add core files.
      [lib/http.js:399](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/http.js#L399)
      Dave Longley commented 9 months ago

  - [ ] FIXME: Remove the startsWith() logic once did-io.get() return signature
      Commit: (6c87cc2) Clarify fixme notes.
      [lib/helpers.js:324](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/helpers.js#L324)
      Dmitri Zagidulin commented 21 days ago

  - [ ] FIXME: Remove the need to specify driver mode
      Commit: (1b7ff74) Add forceConstruct optimization to didIo calls.
      [lib/helpers.js:24](https://github.com/digitalbazaar/bedrock-edv-storage/blob/master/lib/helpers.js#L24)
      Dmitri Zagidulin commented a month ago

**Comment by dlongley** [comment]
Closing as these FIXMEs have been addressed and others have been added as separate issues.
